sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_install:
  - npm i -g nps
after_success:
  - nps semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1200x1024x24"
  - sleep 3
