sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_install:
  - npm i -g nps
after_success:
  - nps semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"